[pytest]
rp_endpoint = https://demo.reportportal.io
rp_project = sathvikatalari_personal
rp_launch = medical_camp_regression_run
rp_launch_attributes = 'Pytest' 'Playwright' 'Automated' 'Docker'
rp_launch_description = 'Automated Test Run for Medical Camp Management System'
rp_ignore_attributes = 'xfail' 'usefixture'
rp_log_level = INFO