# Generated by Django 6.0.5 on 2026-05-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_scansession'),
    ]

    operations = [
        migrations.AddField(
            model_name='scansession',
            name='ocr_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scansession',
            name='ocr_raw_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scansession',
            name='ocr_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
