# Generated by Django 6.0.5 on 2026-05-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_scansession_ocr_data_scansession_ocr_raw_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
