# Generated by Django 6.0.5 on 2026-05-13 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_doctor_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientmedicineissue',
            old_name='strength',
            new_name='formulation',
        ),
    ]
