# Generated by Django 6.0.5 on 2026-05-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_rename_strength_patientmedicineissue_formulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicineissue',
            name='strength',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
