# Generated by Django 6.0.5 on 2026-05-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_patientmedicineissue_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
    ]
