# Generated by Django 6.0.5 on 2026-05-15 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_patientmedicineissue_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='testissue',
            name='vitals_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_tests', to='inventory.patientvitals'),
        ),
    ]
