# Generated by Django 6.0.5 on 2026-05-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_testissue_vitals_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientvitals',
            name='glucose',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='glucose',
        ),
    ]
