# Generated by Django 6.0.5 on 2026-05-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_doctor_is_present'),
        ('inventory', '0037_remove_patientvitals_glucose_remove_vitals_glucose'),
    ]

    operations = [
    ]
