# Generated by Django 6.0.5 on 2026-05-18 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_doctor_is_present'),
        ('inventory', '0038_doctor_is_active'),
    ]

    operations = [
    ]
