# Generated by Django 6.0.5 on 2026-05-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_merge_0036_doctor_is_present_0038_doctor_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='is_present',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('registration_staff', 'Registration Staff'), ('log_vitals_staff', 'Log Vitals Staff'), ('main_admin', 'Main Admin'), ('medicine_entry_staff', 'Medicine Entry Staff')], default='main_admin', max_length=50),
        ),
    ]
