# Generated by Django 6.0.5 on 2026-05-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_remove_doctor_is_present_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='campwisestock',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
