# Generated by Django 6.0.5 on 2026-05-18 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_campwisestock_unit_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampDoctorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_patient_count', models.IntegerField(default=0)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reports', to='inventory.medicalcamp', to_field='number')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.doctor')),
            ],
            options={
                'unique_together': {('camp', 'doctor')},
            },
        ),
    ]
