# Generated by Django 6.0.5 on 2026-05-18 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_campdoctorreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=500)),
                ('patient_id_string', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_patients', to='inventory.medicalcamp')),
            ],
        ),
        migrations.DeleteModel(
            name='CampDoctorReport',
        ),
    ]
