# Generated by Django 6.0.5 on 2026-05-18 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_manualpatientrecord_delete_campdoctorreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpatientrecord',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.doctor'),
        ),
    ]
