# Generated by Django 6.0.5 on 2026-05-19 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_manualpatientrecord_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCampVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('is_new', models.BooleanField(default=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicalcamp', to_field='number')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_visits', to='inventory.patient')),
            ],
            options={
                'db_table': 'patient_camp_visits',
                'unique_together': {('patient', 'camp')},
            },
        ),
    ]
