# Generated by Django 6.0.5 on 2026-05-19 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_patientcampvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcampvisit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_visits', to='inventory.patient', to_field='patient_id'),
        ),
    ]
