# Generated by Django 6.0.5 on 2026-05-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_alter_patientcampvisit_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='campwisestock',
            name='returned_stock',
            field=models.IntegerField(default=0),
        ),
    ]
