# Generated by Django 6.0.5 on 2026-05-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_campwisestock_returned_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='campwisestock',
            name='available_stock',
            field=models.IntegerField(default=0),
        ),
    ]
