# Generated by Django 6.0.5 on 2026-05-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_campwisestock_available_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='campwisestock',
            name='alternate_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
