# Generated by Django 6.0.5 on 2026-05-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_campwisestock_alternate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campwisestock',
            name='company_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='campwisestock',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
