# Generated by Django 6.0.5 on 2026-05-23 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_campwisestock_company_name_campwisestock_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampWiseDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_doctors', to='inventory.medicalcamp')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_doctors', to='inventory.doctor')),
            ],
            options={
                'unique_together': {('camp', 'doctor')},
            },
        ),
    ]
