# Generated by Django 6.0.5 on 2026-05-23 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_campwisedoctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campwisedoctor',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_doctors', to='inventory.medicalcamp', to_field='number'),
        ),
    ]
