# Generated by Django 6.0.5 on 2026-05-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_alter_campwisedoctor_camp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_age',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
