# Generated by Django 6.0.5 on 2026-06-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_medicine_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='testissue',
            name='test_done',
            field=models.BooleanField(default=False),
        ),
    ]
