# Generated by Django 6.0.5 on 2026-05-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_medicine_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='call_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
