# Generated by Django 6.0.5 on 2026-05-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_patient_call_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='latest_call_sid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_retry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
