# Generated by Django 6.0.5 on 2026-07-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_scansession_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='campwisestock',
            name='settled_used',
            field=models.IntegerField(default=0),
        ),
    ]
