# Generated by Django 6.0.5 on 2026-05-27 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0054_medicine_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('retry_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('call_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='voicebot_reminders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_schedules', to='inventory.medicalcamp')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_schedules', to='inventory.patient')),
            ],
        ),
    ]
