# Generated by Django 6.0.5 on 2026-05-27 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_medicine_is_active'),
        ('voicebot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampVoiceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='camp_reminders/')),
                ('telugu_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_reminder', to='inventory.medicalcamp')),
            ],
        ),
    ]
