# Generated by Django 6.0.5 on 2026-05-28 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_medicine_is_active'),
        ('voicebot', '0002_campvoicereminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callschedule',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_schedules', to='inventory.medicalcamp', to_field='number'),
        ),
        migrations.AlterField(
            model_name='callschedule',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_schedules', to='inventory.patient', to_field='patient_id'),
        ),
        migrations.AlterField(
            model_name='campvoicereminder',
            name='camp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_reminder', to='inventory.medicalcamp', to_field='number'),
        ),
    ]
