# Generated by Django 6.0.5 on 2026-05-30 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_medicine_is_active'),
        ('voicebot', '0003_alter_callschedule_camp_alter_callschedule_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('lab_followup', 'Lab Test Follow-up')], default='lab_followup', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('unanswered', 'Unanswered')], default='pending', max_length=20)),
                ('call_sid', models.CharField(blank=True, max_length=200, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_calls', to='inventory.patient', to_field='patient_id')),
                ('test_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_calls', to='inventory.testissue')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=50)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('intent', models.CharField(choices=[('YES', 'Yes – Tests Completed'), ('NO', 'No – Tests Not Completed'), ('PENDING', 'Pending – Appointment Not Done'), ('REPORT_RECEIVED', 'Report Received'), ('REPORT_NOT_RECEIVED', 'Report Not Received'), ('REPORT_PENDING', 'Report Pending'), ('UNCLEAR', 'Unclear / Could Not Understand')], default='UNCLEAR', max_length=30)),
                ('confidence', models.FloatField(default=0.0)),
                ('attempt', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voice_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='voicebot.voicecall')),
            ],
        ),
    ]
