# Generated by Django 6.0.5 on 2026-05-30 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_medicine_is_active'),
        ('voicebot', '0004_voicecall_voiceresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voiceresponse',
            old_name='confidence',
            new_name='confidence_score',
        ),
        migrations.RenameField(
            model_name='voiceresponse',
            old_name='question_key',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='voiceresponse',
            name='attempt',
        ),
        migrations.AddField(
            model_name='voicecall',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voicecall',
            name='test_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_calls', to='inventory.testissue'),
        ),
    ]
